export const TOOLS = [
  {
    name: 'Calculadora de Porcentagem',
    slug: 'calculadora-porcentagem',
    type: 'calculadora',
    category: 'Matemática',
    description: 'Descubra rapidamente quanto representa uma porcentagem de um valor.',
    keywords: ['porcentagem', '%', 'percentual', 'valor base'],
    popular: true,
  },
  {
    name: 'Aumento Percentual',
    slug: 'aumento-percentual',
    type: 'calculadora',
    category: 'Matemática',
    description: 'Calcule um valor com acréscimo percentual aplicado.',
    keywords: ['aumento', 'acréscimo', 'percentual'],
    popular: true,
  },
  {
    name: 'Desconto Percentual',
    slug: 'desconto-percentual',
    type: 'calculadora',
    category: 'Matemática',
    description: 'Aplique desconto percentual e veja o valor final.',
    keywords: ['desconto', 'promoção', 'percentual'],
    popular: true,
  },
  {
    name: 'Regra de Três Simples',
    slug: 'regra-de-tres',
    type: 'calculadora',
    category: 'Educação',
    description: 'Resolva proporções de forma direta e prática.',
    keywords: ['regra de tres', 'proporção', 'x'],
    popular: false,
  },
  {
    name: 'Média Aritmética',
    slug: 'media-aritmetica',
    type: 'calculadora',
    category: 'Educação',
    description: 'Calcule a média de uma lista de números.',
    keywords: ['média', 'notas', 'valores'],
    popular: true,
  },
  {
    name: 'Juros Simples',
    slug: 'juros-simples',
    type: 'calculadora',
    category: 'Financeiras',
    description: 'Descubra juros simples por período.',
    keywords: ['juros', 'capital', 'taxa', 'montante'],
    popular: true,
  },
  {
    name: 'Juros Compostos',
    slug: 'juros-compostos',
    type: 'calculadora',
    category: 'Financeiras',
    description: 'Calcule crescimento composto de investimentos e dívidas.',
    keywords: ['juros compostos', 'investimento', 'taxa'],
    popular: true,
  },
  {
    name: 'Simulador de Parcelas',
    slug: 'simulador-de-parcelas',
    type: 'calculadora',
    category: 'Financeiras',
    description: 'Estime valor da parcela com juros mensais.',
    keywords: ['parcelas', 'financiamento', 'prestação'],
    popular: true,
  },
  {
    name: 'Diferença entre Datas',
    slug: 'diferenca-entre-datas',
    type: 'calculadora',
    category: 'Datas e tempo',
    description: 'Veja a diferença em dias entre duas datas.',
    keywords: ['datas', 'dias', 'intervalo'],
    popular: true,
  },
  {
    name: 'Idade Exata',
    slug: 'idade-exata',
    type: 'calculadora',
    category: 'Datas e tempo',
    description: 'Calcule idade em anos, meses e dias.',
    keywords: ['idade', 'nascimento', 'data'],
    popular: true,
  },
  {
    name: 'Horas Trabalhadas',
    slug: 'horas-trabalhadas',
    type: 'calculadora',
    category: 'Trabalho',
    description: 'Calcule horas trabalhadas com entrada e saída.',
    keywords: ['horas', 'jornada', 'trabalho'],
    popular: false,
  },
  {
    name: 'Horas Extras',
    slug: 'horas-extras',
    type: 'calculadora',
    category: 'Trabalho',
    description: 'Descubra valor de horas extras com adicional.',
    keywords: ['extra', 'trabalho', 'valor hora'],
    popular: false,
  },
  {
    name: 'IMC',
    slug: 'imc',
    type: 'calculadora',
    category: 'Saúde',
    description: 'Calcule seu índice de massa corporal.',
    keywords: ['imc', 'peso', 'altura', 'saúde'],
    popular: true,
  },
  {
    name: 'Consumo de Combustível',
    slug: 'consumo-combustivel',
    type: 'calculadora',
    category: 'Casa e cotidiano',
    description: 'Veja consumo médio do veículo em km/l.',
    keywords: ['combustivel', 'km por litro', 'carro'],
    popular: true,
  },
  {
    name: 'Estimativa de Conta de Luz',
    slug: 'estimativa-conta-luz',
    type: 'calculadora',
    category: 'Casa e cotidiano',
    description: 'Estime gasto mensal de energia elétrica.',
    keywords: ['energia', 'kwh', 'conta de luz'],
    popular: false,
  },
  {
    name: 'km para milha',
    slug: 'km-para-milha',
    type: 'conversor',
    category: 'Comprimento',
    description: 'Converta quilômetros para milhas.',
    keywords: ['km', 'milha', 'comprimento'],
    popular: true,
  },
  {
    name: 'milha para km',
    slug: 'milha-para-km',
    type: 'conversor',
    category: 'Comprimento',
    description: 'Converta milhas para quilômetros.',
    keywords: ['milha', 'km', 'comprimento'],
    popular: false,
  },
  {
    name: 'Celsius para Fahrenheit',
    slug: 'celsius-para-fahrenheit',
    type: 'conversor',
    category: 'Temperatura',
    description: 'Converta graus Celsius para Fahrenheit.',
    keywords: ['celsius', 'fahrenheit', 'temperatura'],
    popular: true,
  },
  {
    name: 'Fahrenheit para Celsius',
    slug: 'fahrenheit-para-celsius',
    type: 'conversor',
    category: 'Temperatura',
    description: 'Converta graus Fahrenheit para Celsius.',
    keywords: ['fahrenheit', 'celsius', 'temperatura'],
    popular: false,
  },
  {
    name: 'kg para libra',
    slug: 'kg-para-libra',
    type: 'conversor',
    category: 'Massa',
    description: 'Converta quilogramas para libras.',
    keywords: ['kg', 'lb', 'massa'],
    popular: true,
  },
  {
    name: 'libra para kg',
    slug: 'libra-para-kg',
    type: 'conversor',
    category: 'Massa',
    description: 'Converta libras para quilogramas.',
    keywords: ['lb', 'kg', 'massa'],
    popular: false,
  },
  {
    name: 'litro para ml',
    slug: 'litro-para-ml',
    type: 'conversor',
    category: 'Volume',
    description: 'Converta litros para mililitros.',
    keywords: ['litro', 'ml', 'volume'],
    popular: false,
  },
  {
    name: 'ml para litro',
    slug: 'ml-para-litro',
    type: 'conversor',
    category: 'Volume',
    description: 'Converta mililitros para litros.',
    keywords: ['ml', 'litro', 'volume'],
    popular: false,
  },
  {
    name: 'horas para minutos',
    slug: 'horas-para-minutos',
    type: 'conversor',
    category: 'Tempo',
    description: 'Converta horas para minutos.',
    keywords: ['hora', 'minuto', 'tempo'],
    popular: false,
  },
  {
    name: 'minutos para horas',
    slug: 'minutos-para-horas',
    type: 'conversor',
    category: 'Tempo',
    description: 'Converta minutos para horas.',
    keywords: ['minutos', 'horas', 'tempo'],
    popular: false,
  },
  {
    name: 'MB para GB',
    slug: 'mb-para-gb',
    type: 'conversor',
    category: 'Digital',
    description: 'Converta megabytes para gigabytes.',
    keywords: ['mb', 'gb', 'digital'],
    popular: true,
  },
  {
    name: 'GB para MB',
    slug: 'gb-para-mb',
    type: 'conversor',
    category: 'Digital',
    description: 'Converta gigabytes para megabytes.',
    keywords: ['gb', 'mb', 'digital'],
    popular: false,
  },
  {
    name: 'Mbps para MB/s',
    slug: 'mbps-para-mbs',
    type: 'conversor',
    category: 'Dev',
    description: 'Converta velocidade em megabits para megabytes por segundo.',
    keywords: ['mbps', 'mb/s', 'internet', 'dev'],
    popular: true,
  },
  {
    name: 'px para rem',
    slug: 'px-para-rem',
    type: 'conversor',
    category: 'Dev',
    description: 'Converta pixels para rem com base de fonte.',
    keywords: ['px', 'rem', 'css', 'dev'],
    popular: true,
  },
  {
    name: 'rem para px',
    slug: 'rem-para-px',
    type: 'conversor',
    category: 'Dev',
    description: 'Converta rem para pixels com base de fonte.',
    keywords: ['rem', 'px', 'css', 'dev'],
    popular: false,
  },
];

export const CALCULATOR_CATEGORIES = [
  'Matemática',
  'Financeiras',
  'Datas e tempo',
  'Trabalho',
  'Saúde',
  'Educação',
  'Casa e cotidiano',
];

export const CONVERTER_CATEGORIES = [
  'Comprimento',
  'Massa',
  'Volume',
  'Temperatura',
  'Área',
  'Velocidade',
  'Tempo',
  'Digital',
  'Energia',
  'Pressão',
  'Ângulo',
  'Dev',
];
